# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Game Development And Other Stupid Decisions
email: hemangsk@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Hello, world!</h3><h1>Game Development And Other Stupid Decisions</h1><h3>Awesome Jekyll Theme for Developers!</h3>Hope you like it!"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ca959971.github.io" # the base hostname & protocol for your site
twitter_username: came4hire
github_username:  ca959971

# Build settings
markdown: kramdown
